### ISSUE TITLE
Interview with Yasmin Hillis

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/stories#5]
Draft finished, awaiting feedback from @rhmnm. Planning to hold the piece until our new website is live (as it will no longer have content related to work in Israel).

Feedback welcome: https://docs.google.com/document/d/1Xae_fAVRPX1M_CISg3GtSp40HzcE28bBJBVaFqQBTLM/edit

**Comment by rhmnm** [comment]
Sorry for the delay. Just reviewed and made a tiny edit. This is such a great interview. Thank you @rebeccaradding for your work and to @yasminhillis for sharing your lovely story and personality with the world!

**Comment by rebeccaradding** [comment]
@rhmnm thank you so much for reviewing! It has been such a pleasure getting to know @yasminhillis and I am excited for her to share her story. I'll connect with you again once our site launches and we are ready to publish the interview around promoting it on social media and elsewhere.

**Comment by rhmnm** [comment]
Great - looking forward to sharing it on our channels as well.

**Comment by rebeccaradding** [comment]
Published!
